import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          navy: '#0D3B75',
          'navy-hover': '#092B57',
          blue: '#1967D2',
          lightbg: '#F5F7FA',
          border: '#E2E8F0',
          textPrimary: '#0F172A',
          textSecondary: '#64748B',
          50: '#eff4ff',
          100: '#dbe7fe',
          500: '#2563eb',
          600: '#1b5eb8',
          700: '#14468f',
          800: '#0f346c',
        },
        surface: {
          DEFAULT: '#f8f9ff',
          dim: '#cbdbf5',
          bright: '#f8f9ff',
          'container-lowest': '#ffffff',
          'container-low': '#eff4ff',
          'container': '#e5eeff',
          'container-high': '#dce9ff',
          'container-highest': '#d3e4fe',
        },
        primary: '#004694',
        'primary-container': '#1b5eb8',
        'on-primary': '#ffffff',
        'on-primary-container': '#ccdbff',
        'inverse-primary': '#acc7ff',
        secondary: '#405f90',
        'on-secondary': '#ffffff',
        'secondary-container': '#a9c7ff',
        'on-secondary-container': '#345383',
        tertiary: '#00524b',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#006c63',
        'on-tertiary-container': '#81eddf',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      spacing: {
        'space-2xs': '0.125rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '0.75rem',
        'space-base': '1rem',
        'space-lg': '1.25rem',
        'space-xl': '1.5rem',
        'space-2xl': '2rem',
        'space-3xl': '2.5rem',
        'sidebar-width': '260px',
        'sidebar-collapsed-width': '72px',
        'profile-bar-height': '80px',
        'gutter-desktop': '1.5rem',
        'gutter-mobile': '1rem',
      },
      borderRadius: {
        'sm': '0.25rem',
        'DEFAULT': '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        'full': '9999px',
      },
    },
  },
  plugins: [],
};
export default config;
